RA-17
alexlenkov-ptn/Recipes pull request #17
Opened 2024-10-18 06:30 UTC by alexlenkov-ptn

2024-10-18 21:20 UTC, alexlenkov-ptn commented
Тут не могу понять почему у меня ведет себя приложение таким образом:
- В запущенном состоянии все ок и состояние активного сердечка сохраняет
- Если я на телефоне закрываю приложение (не сворачиваю), то сердечко снова пустое

2024-10-19 10:37 UTC, alexlenkov-ptn commented
Код скорректировал, теперь работает как задумывалось

Только не понимаю этого коммента из задания:

Во фрагменте RecipeFragment создать метод getFavorites() без принимаемых параметров, который будет возвращать полученную из хранилища изменяемую коллекцию MutableSet<String>. Однако, передавать во вне полученный Set нельзя (об этом говорится в [документации](https://developer.android.com/reference/android/content/SharedPreferences#getStringSet(java.lang.String,%20java.util.Set%3Cjava.lang.String%3E)) . Следует создать новый HashSet, передав в конструктор параметром старый Set.

Для чего нам создавать новый HashSet, когда мы можем просто привести эту строчку к MutableSet и вернуть её?
        val stringSet = sharePrefs.getStringSet("favorites_key", emptySet())

2024-10-19 11:04 UTC, Churickoid requested changes

2024-10-19 11:04 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/RecipeFragment.kt
> +                            saveFavorites(favoritesSet?.toSet() as Set<String>)
Такие преобразования делать опасно, при  favoritesSet = null, твое приложение упадет, поскольку он не сможет преобразовать set. Удобнее будет работать с getFavorites, который возвращает MutableSet<String>, при null просто возвращай пустой hashSet.

2024-10-19 11:15 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/RecipeFragment.kt
> +                if (favoritesSet?.contains(recipeIdString) == true) {
Скорректировал

2024-10-19 11:18 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/RecipeFragment.kt
> +                            saveFavorites(favoritesSet?.toSet() as Set<String>)
Скорректировал

2024-10-19 11:20 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/RecipeFragment.kt
> +        val sharePrefs = context?.getSharedPreferences(
готово

2024-10-20 17:15 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/RecipeFragment.kt
> +            getString(R.string.com_lnkov_recipes_FAVORITES_FILE_KEY),
Вот тут кстати у меня немного другой опыт 

В этой строчке вместо пустого списка 

val stringSet = sharePrefs?.getStringSet(Constants.FAVORITES_KEY, emptySet())

Я ошибочно полагал, что нужно вставить созданный HashSet и поэтому у меня не работало. Изменил на пустой список и все ок

2024-10-20 17:27 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/RecipeFragment.kt
> +            getString(R.string.com_lnkov_recipes_FAVORITES_FILE_KEY),
Готово

2024-10-20 18:11 UTC, Churickoid approved these changes
> Код скорректировал, теперь работает как задумывалось
> 
> Только не понимаю этого коммента из задания:
> 
> Во фрагменте RecipeFragment создать метод getFavorites() без принимаемых параметров, который будет возвращать полученную из хранилища изменяемую коллекцию MutableSet. Однако, передавать во вне полученный Set нельзя (об этом говорится в [документации](https://developer.android.com/reference/android/content/SharedPreferences#getStringSet(java.lang.String,%20java.util.Set%3Cjava.lang.String%3E)) . Следует создать новый HashSet, передав в конструктор параметром старый Set.
> 
> Для чего нам создавать новый HashSet, когда мы можем просто привести эту строчку к MutableSet и вернуть её? val stringSet = sharePrefs.getStringSet("favorites_key", emptySet())

Всё вено! Молодец! 
Когда мы оборачиваем в HashSet, создается новая ячейка в памяти, где хранится список. После этого мы можем его корректно изменять, без этого он на прямую ссылался на ячейку памяти списка из шаред преференсис. Это бы привело к неправильному сохранению префов, после перезапуска приложения менялись бы значения. В доке есть коммент:
Note that you must not modify the set instance returned by this call. The consistency of the stored data is not guaranteed if you do, nor is your ability to modify the instance at all.

2024-10-20 18:15 UTC, merged