RA-20
alexlenkov-ptn/Recipes pull request #19
Opened 2024-10-25 19:05 UTC by alexlenkov-ptn

2024-10-26 13:57 UTC, Churickoid requested changes

2024-10-26 13:57 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +class ViewModelRecipe : ViewModel() {
Все класа в Котлин мы именуем так: сначала уникальное имя, потом родителя. По аналогии с RecipeFragment

2024-10-26 13:57 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val drawable: Drawable? = null
Общий комментарий по дата классам для хранения состояний:

– свойства делаем неизменяемые, тк для его изменения обычно копируется состояние предыдущего стейта с изменением требуемых данных. а не изменяются свойства самого класса
– если есть списки, то стараемся определять их пустыми через listOf() или emptyList()
– стараемся где уместно проставить свойствам значение по умолчанию

2024-10-26 13:57 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val sharePrefs: SharedPreferences? = null,
ШаредПреференсис не относятся к состоянию данных на экране. Мы можем изменить состояние, например, heartIconStatus через него, но само это поле не отражает состояние экрана. Нужно его убрать

2024-10-26 13:57 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val recipeIdString: String? = recipe?.id.toString(),
recipeIdString можно всегда получить через recipe.id.toString(), выделять отдельно его будет неправильно

2024-10-26 13:57 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val favoritesSet: MutableSet<String> = mutableSetOf(),
favoritesSet не отражает стейт экрана, нам достаточно heartIconStatus. Эта переменная излишняя

2024-10-26 13:57 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val drawable: Drawable? = null
Забыл добавить в стейт количество порций, которые мы выбираем. Как раз это отражает наше состояние экрана, мы должны сохранять этот выбор пользователя

2024-10-26 14:34 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +class ViewModelRecipe : ViewModel() {
скорректировал

2024-10-26 14:42 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val drawable: Drawable? = null
Тут сделал: 
- переменные неизменяемыми
- в данном случае реализация списка через mutableSetOf()
- добавил к val heartIconStatus значение по умолчанию

2024-10-26 14:44 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val sharePrefs: SharedPreferences? = null,
готово

2024-10-26 14:46 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val recipeIdString: String? = recipe?.id.toString(),
убрал

2024-10-26 14:53 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/ViewModelRecipe.kt
> +        val drawable: Drawable? = null
Готово

2024-10-27 06:49 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        val numberOfPortions : Int? = null,
Скорректировал

2024-10-27 11:02 UTC, merged