RA-23
alexlenkov-ptn/Recipes pull request #21
Opened 2024-10-28 17:11 UTC by alexlenkov-ptn

2024-10-29 19:00 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
>          arguments?.let {
Готово, сделал

2024-10-29 19:10 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
>              var recipe: Recipe? = null
Вынес в отдельную функцию getRecipe и в начале объявления фрагмента эта переменная инициализириуется

2024-10-29 19:11 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +    private fun updateRecipeUiState(state: RecipeUiState) {
Ожидал, что потом будем использовать. Удалил

2024-10-29 19:13 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +    fun saveFavorites(sharePrefs: SharedPreferences?, stringSet: Set<String>) {
удалил

2024-10-29 19:18 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeUiState.value = _recipeUiState.value?.copy(
Думал тут нужно поставить заглушку. Проинициализировал так, что будем грузить тот рецепт, который изначально и проициниализировали в фрагменте

2024-10-29 19:18 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeUiState.value = _recipeUiState.value?.copy(
Сейчас скорректировал, чтобы поиск был по айди рецепта

2024-10-29 19:33 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeUiState.value = _recipeUiState.value?.copy(isFavorite = heartIconStatus)
Вроде бы понял. Реализовал такую логику, где идет проверка по айдишнику, а возвращается true / false в зависимости от результата

2024-10-29 19:33 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeUiState.value = _recipeUiState.value?.copy(isFavorite = heartIconStatus)
Так необходимо сделать?

2024-10-29 20:19 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        loadRecipe(0)
Вот тут только не до конца понимаю. Оставляем заглушку или нам откуда-то еще должен прилетать recipeId, который нам необходимо использовать в методе?

2024-10-29 20:19 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +        vmRecipe.recipeUiState.observe(viewLifecycleOwner, Observer { state ->
Как я понял для себя тут:

1. При любом методе, который обновляет наш стейт вызывается Observe
2. В классе стейта с помощью метода loadRecipe подгружаются последние обновленные данные стейта
3. Эти данные прилетают в лямбду
4. Данные, которые прилетают в лямбду мы назначаем во Фрагменте, чтобы использовать для отображения в UI

Я правильно это понимаю?))) Хочу просто на всякий для себя уяснить как это работает

Код скорректировал

2024-10-29 20:28 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeUiState.value = _recipeUiState.value?.copy(isFavorite = heartIconStatus)
Тут вроде бы сделал. Но не до конца понимаю для чего мы делаем 2 метода, где первый из них просто проверяет, а другой уже сохраняет в зависимости от результата первого

Что мешает нам реализовать всю эту логику в рамках одного метода?

2024-10-30 10:21 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeUiState.value = _recipeUiState.value?.copy(isFavorite = heartIconStatus)
Внутри viewModel мы можем менять значения в приавтной mutableLiveData, публично мы отдаем обычную liveData, другие классы могут подписываться на неё и слушать изменения значений, но никак менять её они не смогут.
У подписчиков не должно быть привилегий менять значения стейта, поэтому и создаём две переменных

2024-10-30 10:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +    private var isFavorite: Boolean = false
Смысла в этой пременной нет, она будет пораждать лишний рассинхрон, ссылайся только на значения из стейта: state.isFavorite

2024-10-30 10:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        loadRecipe(0)
loadRecipe должен грузить информацию о нажатом Бургере, а не всегда классический бургер. Под заглушкой имеется ввиду, что все эти данные лежат у нас в памяти приложения, а не из сети тянутся. Но эта заглушка должна корректно выводить информацию о кажом из бургеров при нажатии.
Предлагаю  вынести в RecipeFragment.onCreate и по id из аргументов грузить её

2024-10-30 10:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                        vmRecipe.updateNumberOfPortions(portionsCount)
Чтобы не запутываться, верни работу с seekBar как было, в RA-25 мы будем это делать, в текщуем задании про seekBar ничего не написано

2024-10-30 10:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
>          }
У тебя до сих пор используются методы работы с sharePrefs напрямую во фрагменты. Мы переписываем эту логику,  фрагмент ничего не должен содерать о sharedPreferences, всё должно быть скрыто внутри viewModel. Фрагмент только должен получать актуальные данные из observer и менять свой UI в зависимости от нового стейта

2024-10-30 10:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                    vmRecipe.onFavoritesClicked(recipe.id)
setOnClickListener должен только триггерить определенный метод во  viewModel, дальше стейт меняется на уровне viewModel и внутри observer мы отрисовываем ui по новому стейту. Всю логику выше надо почистить от работы с префами и всю ui логику перенести в observer, ссылаясь на стейт

2024-10-30 10:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +        vmRecipe.recipeUiState.observe(viewLifecycleOwner, Observer { recipeState : RecipeViewModel.RecipeUiState ->
В котлин принято выносить последнюю лямбда-функцию за скобки аргументов, поправь
vmRecipe.recipeUiState.observe(viewLifecycleOwner) {state ->}

2024-10-30 10:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +        vmRecipe.recipeUiState.observe(viewLifecycleOwner, Observer { state ->
Всё верно, кроме 4 пункта. Сейчас ты просто создаешь новый дата класс, это неверно и не несет никакого смысла. Внутри observer должна быть прописана логика по которой меняется UI, когда прилетает новый стейт. К примеру, if(recipeState.isFavorite) то тогда кнопка становится нажатой. При нажатии на кнопку мы триггерим метод из viewModel. Получается своебразный черный ящик для фрагмента, мы можем только вызывать у него что-то и получать результат, меняя под него ui, в итоге фрагмент не знает ничего о том, что происходит под копотом viewModel. И так со всеми ui элементами.

2024-10-31 04:59 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                    vmRecipe.onFavoritesClicked(recipe.id)
Я кажется понял. Нам уже в этом задании нужно реализовывать логику, а не просто в VM создать методы. Изначально думал, что мы просто будем создавать методы VM и только в следующих заданиях интегрировать их в логику фрагмента

2024-10-31 05:04 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +    private var isFavorite: Boolean = false
удалил

2024-10-31 05:38 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                    vmRecipe.onFavoritesClicked(recipe.id)
Реализовал 
Теперь VM проверяет есть ли айдишник в SP, затем назначает необходимый стейт и в зависимости от состояния стейта изменяет SP. Все это происходит в VM

2024-10-31 05:42 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +        vmRecipe.recipeUiState.observe(viewLifecycleOwner, Observer { recipeState : RecipeViewModel.RecipeUiState ->
Скорректировал

2024-10-31 05:55 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
>          }
эти методы удалил и заменил на методы VM

2024-10-31 05:59 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                        vmRecipe.updateNumberOfPortions(portionsCount)
Мы до 25 еще не добрались или сейчас нужно реализовать как описано в RA-25 ?

2024-10-31 06:00 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeUiState.value = _recipeUiState.value?.copy(isFavorite = heartIconStatus)
Принял, спасибо)

2024-10-31 06:24 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +        vmRecipe.recipeUiState.observe(viewLifecycleOwner, Observer { state ->
Тогда получается в теле лямбды уже необходимо будет назначать данные для отрисовки фрагмента, которые мы будем получать из стейта?

2024-10-31 06:29 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +        loadRecipe(0)
Готово

2024-10-31 20:10 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                    vmRecipe.onFavoritesClicked(recipe.id)
Да, мы по частям переносим логику на рельсы вью модели. Сейчас работу иконки сердца

2024-10-31 20:13 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                        vmRecipe.updateNumberOfPortions(portionsCount)
Последовательно, сейчас просто это не трогаем, оставляем как было до этого задания

2024-10-31 20:28 UTC, Churickoid commented
Сейчас проект не собирается, твой favoritesFragment зависил от sharedPreferences. Это удаленный метод перенеси в favoritesFragment, чтоб это работало корректно.

Пока ты не совсем понимаешь принцип работы с viewModel. У нас есть vmRecipe.recipeUiState.observe, блок кода внутри отрабатывает каждый раз, когда изминлась liveData, внутри лямбды мы можем получить актуальные данные, обратившись к recipeState: RecipeViewModel.RecipeUiState ->.
Во фрагменты мы должны делать минимум логики, вызывать лишь один метод onFavoritesClicked как это написано в задании.
![image](https://github.com/user-attachments/assets/2134b354-e16d-47ff-829e-aaf7d7687486)
Далее добавление в шаред преференсис происходит внутри функции onFavoritesClicked, когда обновили, меняем наш state из liveData. Значение поменялось, значит затриггерится код в observe с новым стейтом. Внутри observe мы обращаемся к значению recipeState.isFavorite и отрисовываем нажатую или пустую иконку, в зависиомсти от значения.

Также ты удалил что-то лишнее, теперь RecipeFragment пустой

2024-11-01 06:49 UTC, alexlenkov-ptn commented
> Далее добавление в шаред преференсис происходит внутри функции onFavoritesClicked, когда обновили, меняем наш state из liveData. Значение поменялось, значит затриггерится код в observe с новым стейтом. Внутри observe мы обращаемся к значению recipeState.isFavorite и отрисовываем нажатую или пустую иконку, в зависиомсти от значения.

Тут скорректировал
Сейчас код рабочий
По VM изменил следуя твоим комментам
Посмотри, пожалуйста, все ли так?

2024-11-01 21:13 UTC, Churickoid requested changes
Теперь всё верно, молодец! Поправь один коммент в следующем ПР

2024-11-01 21:13 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +        vmRecipe.loadRecipe(getRecipeId(arguments))
Лучше вынести это в onViewCreated, onCreateView как раз и предназначет только для того, чтоб создать view. А стейт отражает наши вьюхи, мы должны его менять, когда они уже создались

2024-11-01 21:14 UTC, Churickoid approved these changes

2024-11-01 22:43 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +                        vmRecipe.updateNumberOfPortions(portionsCount)
Тут сравнил с прошлым заданием и здесь изменений не было, осталось как было ранее

2024-11-01 22:45 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
> +        vmRecipe.loadRecipe(getRecipeId(arguments))
Скорректировал

2024-11-01 22:46 UTC, merged