RA-24
alexlenkov-ptn/Recipes pull request #22
Opened 2024-11-01 23:21 UTC by alexlenkov-ptn

2024-11-02 20:42 UTC, Churickoid requested changes
Молодец, основное заадние выполнение верно! Есть некритичная ошибка, поправь в следующем ПР

2024-11-02 20:42 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/data/recipes.kt
> +    fun getImageUrlById(categoryId: Int, recipesId: Int): String? {
Там где ты используешь этот метод у тебя всегда есть доступ ко всему Recipe, бери url оттуда. Сейчас в loadRecipe ты дважды проходишься по этому списку, сначала для поиска рецепта, потом для поиска url. Лишние затраты ресурсов

2024-11-02 20:42 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +    private fun getDrawable(recipeId: Int?): Drawable? {
Давай лучше передавать recipe в функцию и не едлать лишний поиск

2024-11-03 09:17 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeViewModel.kt
> +    private fun getDrawable(recipeId: Int?): Drawable? {
скорректировал

2024-11-03 09:19 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/data/recipes.kt
> +    fun getImageUrlById(categoryId: Int, recipesId: Int): String? {
Функцию убрал

2024-11-03 09:21 UTC, merged