RA-27
alexlenkov-ptn/Recipes pull request #25
Opened 2024-11-05 07:02 UTC by alexlenkov-ptn

2024-11-05 16:25 UTC, alexlenkov-ptn commented
Пока что сделал View Model для фрагмента Recipes List Fragment
Можешь посмотреть и оставить обратную связь, пожалуйста?

2024-11-05 20:26 UTC, Churickoid requested changes
Сделал всё верно, доделай экран избранного и категорий

2024-11-05 20:26 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListFragment.kt
> +            recipesListAdapter.setOnItemClickListener(
Здесь не происходит никаких взаимодействий с данными из стейта, при изменении стейта будет повторно создаваться новый объект object : RecipesListAdapter.OnItemClickListener и привязываться к адаптеру. Давай вынесем из observer

2024-11-05 20:26 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/favorites/FavoritesFragment.kt
> +
Из этого фрагмента удалить уже нужно удалить getFavorites, добавить observer и менять значения адаптера внутри из данных стейта, почти также как и на экране рецептов

2024-11-06 05:03 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListFragment.kt
> +            recipesListAdapter.setOnItemClickListener(
Тут скорректировал. Добавил метод, который будет обновлять данные адаптера, а не заново пересоздавать адаптер. Иначе получалось, что клик привязывался к пустому списку, который пересоздавался в observe

2024-11-06 06:15 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/favorites/FavoritesFragment.kt
> +
Да, на тот момент еще не доделал здесь
Сейчас сделал

2024-11-06 13:41 UTC, Churickoid approved these changes
Всё верно по текущему заданию. Молодец! Поправь в следующем ПР проблему из коммента

2024-11-06 13:41 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe/RecipeFragment.kt
>                  ibIcHeart.setOnClickListener { viewModel.onFavoritesClicked() }
Из observer в RecipeFragment тоже нужно вынести все строки, которые не зависят от данных стейта. Это касается и этой строки, и установки divider. Покрути сикбар на этом экране - адаптер начинает расти в длину. Это связано с тем, что после каждого изменения стейта прикрепляется новый divider к предыдущем

2024-11-06 13:43 UTC, merged