RA-28
alexlenkov-ptn/Recipes pull request #26
Opened 2024-11-06 14:06 UTC by alexlenkov-ptn

2024-11-07 09:34 UTC, alexlenkov-ptn commented
Ещё заметил такой баг по приложению на текущем этапе:
- Добавляем рецепт в избранное
- Заходим в избранное
- Падаем снова в этот рецепт
- Жмем на сердечко, рецепт убирается из избранного
- Уходим на прошлый экран кнопкой назад
- Рецепт по прежнему продолжает отображаться во вью

Если переходим нажимая по кнопке "Избранное", то рецепта уже нет

Это на текущем этапе где-то скорректировать нужно или в след этапах ?

2024-11-07 16:08 UTC, Churickoid requested changes

2024-11-07 16:08 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListFragment.kt
> +        findNavController().navigate(R.id.recipeFragment, bundle)
Фрагменты между собой должны перемещаться через action, для этого в nav_graph нужно соединить стрелочками
Для action можно прописать параметр app:launchSingleTop="true", так он будет открываться лишь единожды. Это должно пофиксить твой баг.
Все переходы между фрагментами должны выполняться через action, а не напрямую

Попробуй 10 раз подряд нажать на кнопку Категорий, все они попадут в backstack, чтобы их все закрыть придется нажать 10 раз на кнопку назад. 
Для фрагментов из MainActivity фикс выше не сработает, поскольку они без action, из-за того что упраляются через родился. Придется сделать по другому, создать navOptions и прописать эти настройки там.
![image](https://github.com/user-attachments/assets/f1951d74-d55a-436d-9e3d-dcc53f653b92)

2024-11-07 18:09 UTC, alexlenkov-ptn commented on app/build.gradle.kts
> +    androidTestImplementation("androidx.navigation:navigation-testing:$nav_version")
скорректировал

2024-11-08 05:00 UTC, alexlenkov-ptn commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/clMain"
Тут при изменении нейминга в активити мэйн почему-то изменилось тоже. Скорректировал

2024-11-08 05:47 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListFragment.kt
> +        findNavController().navigate(R.id.recipeFragment, bundle)
Тут скорректировал, но этот баг по прежнему остался

По сути когда мы нажимаем кнопку Favorites у нас срабатывают функцию VM и следовательно создание SP

А когда мы нажимаем кнопку назад как будто эти функцию не срабатывают, не обновляются, следовательно вьюшка не перерисовывается и остается в исходном состоянии

Вот можно как-то повлиять на эту кнопку? Чтобы при нажатии назад SP обновлялся и вьюшка перерисовывалась с учетом нового значения SP

2024-11-08 05:48 UTC, alexlenkov-ptn commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/clMain"
Скорректировал

2024-11-08 09:18 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListFragment.kt
> +        findNavController().navigate(R.id.recipeFragment, bundle)
Я нашёл в чем баг заключается 

В VM Избранного я в отдельную переменную записывал значения SP
Как я понял после кнопки назад это значение не обновлялось, сейчас вместо переменной сделал функцию, которая при вызове обращается к SP и даёт актуальные значения

2024-11-08 20:20 UTC, Churickoid approved these changes
Молодец! Всё верно сделал и сам обноружил решения бага.
Твой баг был связана с тем, что у тебя вызывается onViewCreated -> loadRecipes при возврате на фрагмент, который ссылался на протухшие данные из переменной, а не брал актуальные. 
Поправь один коммент в следующем ПР

2024-11-08 20:20 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/favorites/FavoritesFragment.kt
> +        findNavController().navigate(R.id.recipeFragment, bundle)
Ты сгенерировал action, но так их и не используешь, нужно в этих местах передавать id экшена, а не фрагмента, чтоб изменения вступили в силу. Сделай это со всеми фрагментами

2024-11-09 04:37 UTC, merged