RA-30
alexlenkov-ptn/Recipes pull request #28
Opened 2024-11-09 04:57 UTC by alexlenkov-ptn

2024-11-10 18:19 UTC, Churickoid requested changes
При переходе по кнопкам нету анимации. Добавь navOptions { 
    anim {
        ....
    }
  }

2024-11-10 18:19 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/categories/CategoriesListFragment.kt
> +        val category = STUB.getCategoryById(categoryId)
Вся работа с данными выполняется ВьюМоделью, это нарушение принципа MVVM. Актуальный источник данных это стейт внутри observer, значит листенер должен получать данные из этого стейта внутри observer

2024-11-10 18:19 UTC, Churickoid commented on gradle/libs.versions.toml
> +navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref ="navigationSafeArgsGradlePlugin" }
Эта библиотека часть navigation, ты уже создавал переменную navVersion, используй её. Рассинхрон версий может поломать билд приложения

2024-11-11 07:12 UTC, alexlenkov-ptn commented
> При переходе по кнопкам нету анимации. Добавь navOptions { anim { .... } }

Вот тут я не совсем понял как это создается
Нашел способ как создать программно анимации в MainActivity

2024-11-11 07:13 UTC, alexlenkov-ptn commented on gradle/libs.versions.toml
> +navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref ="navigationSafeArgsGradlePlugin" }
Скорректировал

2024-11-11 07:37 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/categories/CategoriesListFragment.kt
> +        val category = STUB.getCategoryById(categoryId)
Сделал листенер внутри observer

2024-11-11 07:41 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/categories/CategoriesListFragment.kt
> +        val category = STUB.getCategoryById(categoryId)
только вот критично ли, что листенер будет каждый раз создаваться при открытии этого фрагмента

2024-11-11 20:22 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/MainActivity.kt
> +        )
Твоя конструкция рабочая, но она всё таки устаревшая. Я хотел, чтоб ты её обновил с использованием блока anim{ }
```
private val navOptions = navOptions {
    launchSingleTop = true
    anim {
        enter = 
        exit = 
        popEnter = 
        popExit  =
}
```

2024-11-11 20:22 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/categories/CategoriesListFragment.kt
> +        val category = STUB.getCategoryById(categoryId)
По ресурсом это также как поменять цвет кнопки, если не меньше. Но нам приоритетнее, чтоб везде были актуальные данные во фрагменте, так что этим незначительным лишним вызовом можно пренебречь

2024-11-11 20:23 UTC, Churickoid approved these changes
Молодец, cделал всё верно! Обнови в следующем ПР конструкцию для navOption

2024-11-12 07:32 UTC, merged