RA-40
alexlenkov-ptn/Recipes pull request #38
Opened 2024-11-26 19:02 UTC by alexlenkov-ptn

2024-11-26 19:18 UTC, alexlenkov-ptn commented
Тут реализовал по такой логике:
category загружаю по входящему categoryId, который я нахожу в локальной БД Category

Далее если входящий categoryId в RecipesVM fun loadCategory не равен загруженному ранее, то значит нам нужен другой список, который мы будем подгружать. 
В теле условия удаляем чистим БД Recipe, подгружаем новый список по айдишке категории

Ещё думал над реализацией такого способа, но мне он показался не канон и немного странный. 

Если кол-во рецептов останется без изменений, то вполне рабочий и удобный:
У каждого рецепта ID состоит из трех знаков, первый знак соответствует ID категории
Можно добавить метод, который бы выгружал нам только те значения, которые начинаются с первого символа в ID
Либо как-то иначе реализовать с добавлением нового поля в эту таблицу, где айди категории дублировалось бы

2024-11-26 20:43 UTC, Churickoid requested changes
Давай в рамках текущей ПР еще переделаем RecipeViewModel, чтоб она работала только на кэше, без интернета. Оптимизируем количество хождений в сеть. За одно и проверим все ли данные кешируется верно

2024-11-26 20:43 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/data/RecipeRepository.kt
> +    ).build()
Давай добавлять параметр .fallbackToDestructiveMigration() для базы данных. Так не придется очищать руками кэш приложения для корректной работы на новой версии.

2024-11-26 20:43 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListViewModel.kt
> +                    loadRecipesToCache(recipeList)
Предлагаю отказаться от текущей реализации, основная проблема этого подхода - как такового кэша и нет, только на одной странице рецептах и только при условиях определенных.
Нужно добавить механизм получения рецептов по конкретной категории. Давй в Recipe пропишем еще параметр categoryId, по аналогии с isFavourite. По умолчанию он будет -1, при закидывании в бд проставлять его и заполнять таблицу. При открытии делать запрос по categoryId

2024-11-27 06:43 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/data/RecipeRepository.kt
> +    ).build()
Добавил

2024-11-27 18:43 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListViewModel.kt
> +                    category?.id != recipeListUiState.value?.category?.id
Сейчас на экране рецептов не работает кэширование. С выключенным интернетом - пустой список. Это связано с этим условием. У тебя по умолчанию category = null, из-за этого id будет сравниваться с null. Давай его уберем полностью

2024-11-27 18:45 UTC, Churickoid commented on gradle/libs.versions.toml
> +roomCommon = "2.6.1"
плодить одинаковые версии не надо, создай одну переменнуб room и указывай эту версию всем рум либам. Так не будет никакого конфликта версий

2024-11-27 18:46 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/ui/categories/CategoriesDao.kt
> +interface CategoriesDao {
Сами ДАО это механизм для получения данных из таблицы базы данных. Они не имеют никакого отношения к UI слою, это источник данных для репозитория. Перенеси их в папку data
https://developer.android.com/topic/architecture/data-layer?hl=ru

2024-11-27 19:28 UTC, merged

2024-11-27 19:44 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/ui/recipes/recipe_list/RecipesListViewModel.kt
> +                    category?.id != recipeListUiState.value?.category?.id
Скорректировал