RA-45
alexlenkov-ptn/Recipes pull request #42
Opened 2024-11-29 16:08 UTC by alexlenkov-ptn

2024-11-30 17:49 UTC, Churickoid requested changes

2024-11-30 17:49 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/data/RecipeRepository.kt
> +    private val dispatcher : CoroutineContext = Dispatchers.IO
В прошлых ПР писал, что диспатчер рекомендуется выносить в конструктор. Без этого юнит-тесты не написать на код. Реализуй в модуле хилта инжект диспатчера
https://medium.com/@kursatkumsuz/how-to-inject-coroutine-dispatchers-using-hilt-39d99a33824b

2024-11-30 17:49 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/data/RecipeRepository.kt
> +        appDatabase.categoryDao().getAll()
Давать репозиторию доступ ко всей базе данных - не очень безопасно. Ты в модуле прописал уже конкретные ДАО, нужно их и инжектить.  Поправь для всех функций

2024-11-30 17:49 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/di/RecipeModule.kt
> +    @Provides
Почитай еще про аннотацию @singleton. Если сейчас Database заинджектится куда-то в другое место, создастся новый объект, может произойти рассинхрон между данными. Добавь эту аннотацию, где уместно

2024-11-30 17:49 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/di/FavoritesViewModelFactory.kt
> +class FavoritesViewModelFactory(
Этот код уже нигде не используется, если хочешь - можешь оставить

2024-12-01 09:06 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/data/RecipeRepository.kt
> +    private val dispatcher : CoroutineContext = Dispatchers.IO
Готово

2024-12-01 09:07 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/di/FavoritesViewModelFactory.kt
> +class FavoritesViewModelFactory(
удалил

2024-12-01 09:11 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/di/RecipeModule.kt
> +    @Provides
Как я понял нам для проекта в Singleton понадобятся все классы, нет необходимости пересоздавать несколько их копий

2024-12-01 09:20 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/data/RecipeRepository.kt
> +        appDatabase.categoryDao().getAll()
Реализовали через Дао

2024-12-01 09:21 UTC, alexlenkov-ptn commented on app/src/main/java/com/lnkov/recipes/di/RecipeModule.kt
> +    @Provides
А есть ли смысл в целом модуль сделать через object ? На практике попробовал - с приложением вроде всё ок, проблем не возникает

2024-12-01 17:23 UTC, Churickoid commented on app/src/main/java/com/lnkov/recipes/di/RecipeModule.kt
> +    @Provides
В целом никакого смысла нет, можно и так и так использовать. Вижу только плюс использовать class вместо object - более легкая совместимость с java кодом

2024-12-01 17:24 UTC, Churickoid approved these changes
Всё верно,  молодец!

2024-12-01 18:19 UTC, merged